### ISSUE TITLE
Compressed images with OMP / 100 ROM

### ISSUE THREAD

**Issue by ghost** [pablomarx/Leibniz#2]
Hi, thanks for this great too. I notice, that the displayed images it compressed while emulating a OMP / 100 / Notepad. Works fine with a 120 rom. Maybe it's the screen size? 
![leibnitz](https://user-images.githubusercontent.com/7260857/71321852-e5bddc00-24bf-11ea-8772-108f61967430.png)

**Comment by pablomarx** [comment]
@nasendackel This appears to be an issue in recent macOS versions.  I've applied a change which fixes it on my end (macOS 10.14.6).  

Are you able to build the app from Xcode, or are you using a pre-built binary?

**Comment by ghost** [comment]
@pablomarx Thank you so much. I just compiled it in Xcode. Works fine now in 10.15.2. 
![Bildschirmfoto 2019-12-22 um 20 01 02](https://user-images.githubusercontent.com/7260857/71326050-f25d2700-24f5-11ea-84af-f1399f786b56.png)
